/* SPDX-License-Identifier: GPL-2.0-only */

#include <southbridge/intel/lynxpoint/lp_gpio.h>

const struct pch_lp_gpio_map mainboard_gpio_map[] = {
	LP_GPIO_OUT_LOW, /* 0: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL }, /* 1 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 2 */
	LP_GPIO_OUT_LOW, /* 3: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 4: NATIVE */
	LP_GPIO_NATIVE, /* 5: NATIVE */
	LP_GPIO_NATIVE, /* 6: NATIVE */
	LP_GPIO_NATIVE, /* 7: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 8 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 9 */
	LP_GPIO_OUT_LOW, /* 10: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 11: NATIVE */
	LP_GPIO_NATIVE, /* 12: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 13 */
	LP_GPIO_OUT_LOW, /* 14: OUTPUT LOW */
	LP_GPIO_OUT_LOW, /* 15: OUTPUT LOW */
	LP_GPIO_OUT_HIGH, /* 16: OUTPUT HIGH */
	LP_GPIO_OUT_LOW, /* 17: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 18: NATIVE */
	LP_GPIO_NATIVE, /* 19: NATIVE */
	LP_GPIO_NATIVE, /* 20: NATIVE */
	LP_GPIO_NATIVE, /* 21: NATIVE */
	LP_GPIO_NATIVE, /* 22: NATIVE */
	LP_GPIO_NATIVE, /* 23: NATIVE */
	LP_GPIO_OUT_LOW, /* 24: OUTPUT LOW */
	LP_GPIO_OUT_LOW, /* 25: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 26 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 27 */
	LP_GPIO_OUT_LOW, /* 28: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 29: NATIVE */
	LP_GPIO_NATIVE, /* 30: NATIVE */
	LP_GPIO_NATIVE, /* 31: NATIVE */
	LP_GPIO_NATIVE, /* 32: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 33 */
	LP_GPIO_OUT_HIGH, /* 34: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 35 */
	LP_GPIO_OUT_LOW, /* 36: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 37: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 38 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 39 */
	LP_GPIO_NATIVE, /* 40: NATIVE */
	LP_GPIO_NATIVE, /* 41: NATIVE */
	LP_GPIO_NATIVE, /* 42: NATIVE */
	LP_GPIO_NATIVE, /* 43: NATIVE */
	LP_GPIO_OUT_LOW, /* 44: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL, .route = GPIO_ROUTE_SMI, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 45 */
	LP_GPIO_OUT_LOW, /* 46: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 47 */
	LP_GPIO_OUT_LOW, /* 48: OUTPUT LOW */
	LP_GPIO_OUT_LOW, /* 49: OUTPUT LOW */
	LP_GPIO_OUT_HIGH, /* 50: OUTPUT HIGH */
	LP_GPIO_OUT_LOW, /* 51: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 52 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 53 */
	LP_GPIO_OUT_LOW, /* 54: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT, .pirq = GPIO_PIRQ_APIC_ROUTE }, /* 55 */
	LP_GPIO_OUT_HIGH, /* 56: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 57: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 58 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 59 */
	LP_GPIO_OUT_LOW, /* 60: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 61: NATIVE */
	LP_GPIO_NATIVE, /* 62: NATIVE */
	LP_GPIO_NATIVE, /* 63: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 64 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 65 */
	LP_GPIO_OUT_LOW, /* 66: OUTPUT LOW */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL }, /* 67 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL }, /* 68 */
	LP_GPIO_OUT_HIGH, /* 69: OUTPUT HIGH */
	LP_GPIO_OUT_LOW, /* 70: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 71: NATIVE */
	LP_GPIO_NATIVE, /* 72: NATIVE */
	LP_GPIO_OUT_LOW, /* 73: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 74: NATIVE */
	LP_GPIO_NATIVE, /* 75: NATIVE */
	LP_GPIO_OUT_HIGH, /* 76: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 77 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL, .route = GPIO_ROUTE_SMI }, /* 78 */
	LP_GPIO_NATIVE, /* 79: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL }, /* 80 */
	LP_GPIO_NATIVE, /* 81: NATIVE */
	LP_GPIO_NATIVE, /* 82: NATIVE */
	LP_GPIO_OUT_HIGH, /* 83: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 84: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 85: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL }, /* 86 */
	LP_GPIO_OUT_LOW, /* 87: OUTPUT LOW */
	LP_GPIO_OUT_LOW, /* 88: OUTPUT LOW */
	LP_GPIO_OUT_HIGH, /* 89: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 90: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 91 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT | GPIO_IRQ_LEVEL }, /* 92 */
	LP_GPIO_OUT_LOW, /* 93: OUTPUT LOW */
	LP_GPIO_OUT_LOW, /* 94: OUTPUT LOW */
	LP_GPIO_END
};