/* SPDX-License-Identifier: GPL-2.0-only */

#include <southbridge/intel/lynxpoint/lp_gpio.h>

const struct pch_lp_gpio_map mainboard_gpio_map[] = {
	LP_GPIO_OUT_HIGH, /* 0: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 1: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 2: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 3: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 4: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 5: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 6: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 7: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 8: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 9: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 10: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 11: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 12: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 13: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 14: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 15 */
	LP_GPIO_OUT_HIGH, /* 16: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 17: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 18: OUTPUT HIGH */
	LP_GPIO_NATIVE, /* 19: NATIVE */
	LP_GPIO_NATIVE, /* 20: NATIVE */
	LP_GPIO_NATIVE, /* 21: NATIVE */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT, .owner = GPIO_OWNER_GPIO }, /* 22 */
	LP_GPIO_OUT_HIGH, /* 23: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 24: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 25: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 26: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 27: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 28: OUTPUT HIGH */
	LP_GPIO_NATIVE, /* 29: NATIVE */
	LP_GPIO_OUT_HIGH, /* 30: OUTPUT HIGH */
	LP_GPIO_NATIVE, /* 31: NATIVE */
	LP_GPIO_OUT_HIGH, /* 32: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 33: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 34: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 35: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 36: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 37: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 38: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_INVERT }, /* 39 */
	LP_GPIO_NATIVE, /* 40: NATIVE */
	LP_GPIO_NATIVE, /* 41: NATIVE */
	LP_GPIO_OUT_HIGH, /* 42: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 43: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 44: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 45: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 46: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 47: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 48: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 49 */
	LP_GPIO_OUT_HIGH, /* 50: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 51: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 52: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 53: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 54: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 55: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 56: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 57: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 58: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 59: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 60: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 61: OUTPUT HIGH */
	LP_GPIO_NATIVE, /* 62: NATIVE */
	LP_GPIO_NATIVE, /* 63: NATIVE */
	LP_GPIO_OUT_HIGH, /* 64: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 65: OUTPUT HIGH */
	LP_GPIO_NATIVE, /* 66: NATIVE */
	LP_GPIO_OUT_HIGH, /* 67: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 68: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 69: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 70: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 71: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 72: OUTPUT HIGH */
	LP_GPIO_OUT_LOW, /* 73: OUTPUT LOW */
	LP_GPIO_NATIVE, /* 74: NATIVE */
	LP_GPIO_NATIVE, /* 75: NATIVE */
	LP_GPIO_INPUT, /* 76: LP_GPIO_INPUT */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT, .owner = GPIO_OWNER_GPIO }, /* 77 */
	LP_GPIO_OUT_HIGH, /* 78: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 79: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 80: OUTPUT HIGH */
	LP_GPIO_NATIVE, /* 81: NATIVE */
	LP_GPIO_NATIVE, /* 82: NATIVE */
	LP_GPIO_OUT_HIGH, /* 83: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 84: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 85: OUTPUT HIGH */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 86 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 87 */
	{ .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT }, /* 88 */
	LP_GPIO_OUT_HIGH, /* 89: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 90: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 91: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 92: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 93: OUTPUT HIGH */
	LP_GPIO_OUT_HIGH, /* 94: OUTPUT HIGH */
	LP_GPIO_END
};